import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../layouts/Layout";

const Home: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Synanto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <p>home</p>
        </Layout>
      </div>
    )
};

export default Home;
