import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../layouts/Layout';
import { useSession } from 'next-auth/react';
import { useEffect } from 'react';
import Router from 'next/router';

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  useEffect(() => {
    if (status === 'unauthenticated') Router.replace("/auth/signin");
  });

  if (status === 'authenticated') 
    return (
      <div>
        <Head>
          <title>Synanto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <p>home</p>
        </Layout>
      </div>
    )

  return <div>Loading...</div>;
};

export default Home;
